
package Interfaz;

import Dominio.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;


public class Ranking extends javax.swing.JFrame implements Observer {
    
   Sistema sis;

    /** Creates new form Ranking */
    public Ranking (Sistema s) {
        sis = s;
        //le agrego el observer a los jugadores
        for(int m=0;m<sis.getListaDeJugadores().size(); m++){
            sis.getListaDeJugadores().get(m).addObserver(this);
            }
        //le agrego el observer al sistema
        sis.addObserver(this);
        initComponents();
        //Pongo para que la tabla no sea editable
        tabla.setEnabled(false);
        this.setTitle("Ranking");
        update(null, null);        
    }

       //metodo para agregar las filas
	private void agregarFila(int cantfila){
        int filas=0;
	// se crea un modelo para la tabla, el nombre de la variable de la tabla es: tabla
	DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();

	//se agrega la fila en la tabla con un valor vacio
        while(modelo.getRowCount()<=cantfila){
            modelo.addRow(new Object[filas]);
            filas++;
        }
		
    }

        public void update(Observable o, Object arg) {
        ArrayList<Jugador> cloJ = (ArrayList<Jugador>) sis.getListaDeJugadores().clone();
        Sistema.ordenar(cloJ);
       
        //Llamo al metodo que me devuelve la lista ordenada
        agregarFila(cloJ.size());

        //lleno la tabla con los datos
        for (int i=0; i<cloJ.size(); i++){            
            tabla.setValueAt(cloJ.get(i).getNombre(), i, 0);
            tabla.setValueAt(Integer.toString(cloJ.get(i).getPartidosGanados()), i, 1);
            tabla.setValueAt(Integer.toString(cloJ.get(i).getJuegosJugados()), i, 2);
        }
    }        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaRankings = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Partidas Ganadas", "Juegos Jugados"
            }
        ));
        tablaRankings.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(tablaRankings, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(tablaRankings, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tabla;
    private javax.swing.JScrollPane tablaRankings;
    // End of variables declaration//GEN-END:variables

}
